const CONSTANTS = {
  TAB_LIST: {
    HOME: "Home",
    MARKETING: "Marketing",
    CROPS: "Crops",
    SETTINGS: "Settings",
    TASK: "Task",
  },
  HEADER_TITLE: {
    MY_FARM_LAND: "MyFarmLand",
    TODAY_OVERVIEW: "Today Overview",
  },
  ANIMAL_LIST: {
    COW: "Cow",
    GOAT: "Goat",
    CHICKEN: "Chicken",
    TO_DO: "ToDo",
  },
  HOME_ACTION_LIST: {
    ANIMAL_MANAGEMENT: "Animal Management",
    FEEDING_SCHEDULE: "Feeding Schedule",
    CROP_MANAGEMENT: "Crop Management",
    FARM_TASK: "Farm Tasks",
  },
  LOG_IN: {
    WELCOME_MY_FARM: "Welcome to my farm land",
    WELCOME_MY_FARM_MESSAGE: "Manage your farm anytime,anywhere.",
    ENTER_MOBILE_NUMBER: "Enter your mobile number",
    TERMS: "Terms",
    AND: "and",
    PRIVACY_POLICY: "Privacy policy",
    AGREE: "By continuing, you agree to our",
    SEND_OTP: "Send OTP",
    VERIFY_OTP: "Verify OTP",
    ENTER_OTP_VERIFY: "Enter OTP to verify",
    OTP_VERIFY_MESSAGE:
      "We've  sent a 6-digit code to your mobile number +91xxxxxxxxxx.Please enter it below",
    DONT_RECEIVE_OTP: "Don't receive the OTP?",
    RESEND: "Resend",
  },
  PREVIOUS: "Previous",
  NEXT: "Next",
  FARM_SETUP: "Farm Setup",
  BASIC_FARM_DETAIL: "Basic Information about your Farm",
  FARM_SIZE_DETAIL: "Set up your farm size ans location",
  ANIMAL_SIZE_DETAIL: "Choose the animal you raise ",
  STEP_of_1: "Step 1 of",
  FARM_DETAIL: {
    NO_FARM_DETAILS_FOUND: "No Farm Details Found",
    FARM_SETUP_MESSAGE: "It Looks like you havenot set up a farm yet",
    CREATE_FARM: "Create Farm",
    WELCOME_TO_FARM_FLOW: "Welcome to Farmflow",
    DIGITAL_FARM_MANAGEMENT: "Your Digital farm management companion",
    FARM_DETAIL: " Farm Name :*",
    FARM_LOCATION: "Farm Location :",
    TOTAL_AREA: "Total Area: *",
    UNIT: "Unit: *",
  },
};
export default CONSTANTS;
